### ISSUE TITLE
[缺陷]TPagination 第一页时会显示两个第一页的页码

### ISSUE THREAD

**Issue by wuxinheng** [tdesign-blazor/TDesignBlazor#243]
#### 详细描述
1.TPagination 三个参数都是1，
<img width="646" alt="image" src="https://user-images.githubusercontent.com/49859025/221866238-e6bc8770-4b1e-41e3-82cf-f9d7cfa0cd09.png">
实际效果图
<img width="731" alt="image" src="https://user-images.githubusercontent.com/49859025/221866415-58a9a915-4495-4143-88ae-4fa4dd288019.png">

#### 重现步骤
1. 正常赋值

#### 期望结果
只有一页可以点击

#### 托管方式
- [x] Blazor Server
- [ ] Blazor WebAssembly

#### 浏览器版本
- [ ] Edge
- [ ] Chrome
- [ ] Firefox
- [ ] 其他

#### 备注
是否还有其他的关于该问题的补充内容

**Comment by wuxinheng** [comment]
maui

**Comment by AchievedOwner** [comment]
> maui

你试试看 WebAssembly 项目是否也有同样的问题
