### ISSUE TITLE
http://tblazor.com 访问不到

### ISSUE THREAD

**Issue by nodyang** [tdesign-blazor/TDesignBlazor#292]
#### 详细描述
尽可能的详细描述

#### 重现步骤
1. ...
2. ...
3. ...
4. ...

#### 期望结果
清晰且详细地描述你期望达到的结果

#### 托管方式
- [ ] Blazor Server
- [ ] Blazor WebAssembly

#### 浏览器版本
- [ ] Edge
- [ ] Chrome
- [ ] Firefox
- [ ] 其他

#### 备注
是否还有其他的关于该问题的补充内容

**Comment by AchievedOwner** [comment]
已经修复
